-- CreateEnum
CREATE TYPE "FraudRisk" AS ENUM ('SAFE', 'SUSPICIOUS', 'HIGH_RISK');

-- AlterTable
ALTER TABLE "User" ADD COLUMN "clerkId" TEXT,
ALTER COLUMN "passwordHash" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Student" ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Gig" ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ReputationScore" ADD COLUMN "reliabilityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "workIdentityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "totalCompleted" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "punctualityCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "positiveReviews" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "cancellations" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "noShows" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "fakeReports" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "fraudStatus" "FraudRisk" NOT NULL DEFAULT 'SAFE';

-- CreateIndex
CREATE UNIQUE INDEX "User_clerkId_key" ON "User"("clerkId");
